### ISSUE TITLE
Unable to specify prerelease versions of Visual Studio 

### ISSUE THREAD

**Issue by MarkIngramUK** [darenm/Setup-VSTest#15]
[microsoft/setup-msbuild](https://github.com/microsoft/setup-msbuild) allows the following input:

```
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
```

Which adds the `-prerelease` flag to the command line to `vswhere`:
> vswhere.exe -products * -requires Microsoft.Component.MSBuild -property installationPath -latest -prerelease

This allows setup-msbuild to work with the `windows-2022` runner which ships with Visual Studio 2022 Preview installed. Without the `-prerelease` flag, `vswhere` will not find `MSBuild` / `VSTest`.
